apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myAzFile
provisioner: file.csi.azure.com
#reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
   skuName: Standard_LRS
