kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: nginx:latest
      resources:
        requests:
          cpu: 100m
          memory: 128mi
        limits:
          cpu: 200m
          memory: 270Mi
      volumeMounts:
       - mountPath: /mnt/azure
         name: volume
      volumes:
        - name: volume
        persistentVolumeClaim:
          claimName: myAzFile 